# Generated by Django 3.0 on 2019-12-16 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('initial_blockly_workspace', models.TextField(default='\n        <xml>\n            <block type="simulation_loop" id="initial_loop" x="36" y="32" deletable="false" movable="false"></block>\n        </xml>\n        ')),
            ],
        ),
        migrations.CreateModel(
            name='Lobby',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Lobby', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blockly_workspace', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player_one', models.CharField(max_length=50, null=True)),
                ('player_two', models.CharField(max_length=50, null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='battle.Game')),
            ],
        ),
    ]
